# https://starship.rs/config/

"$schema" = 'https://starship.rs/config-schema.json'

format = """
(#88c0d0)\
$directory\
$git_branch$git_commit$git_state$git_metrics$git_status\
$line_break\
$character\
"""

[git_branch]
format = "[ $symbol$branch(:$remote_branch) ]($style)"
symbol = " "
style = "fg:#81a1c1"

[git_status]
format = "[$ahead_behind$diverged$stashed$staged$untracked$modified$conflicted]($style)"
style = "fg:#8fbcbb"
ahead="↑${count}"
behind=" ↓${count}"
conflicted = " ×${count}"
diverged = ' ⇕⇡${ahead_count}⇣${behind_count}'
modified=" ~${count}"
staged=" +${count}"
stashed=" \\$${count}"
untracked=" ?${count}"

[shell]
disabled = false

[directory]
format = "[» $path ]($style)"
style = "fg:#5e81ac"
truncate_to_repo = true
truncation_length = 4

[character]
success_symbol = "[\\$](#88c0d0)"
error_symbol = "[\\$](#88c0d0)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
disabled = true

[nodejs]
disabled = true

