# https://yazi-rs.github.io/docs/configuration/keymap
# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap-default.toml

"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  # Hopping
  { on = "{" , run = "arrow -6", desc = "Move cursor 6 items up"},
  { on = "}" , run = "arrow 6", desc = "Move cursor 6 items up"},
  { on = [ "<c-n>" ], run = "arrow 1", desc = "Move cursor down" },
  { on = [ "<c-p>" ], run = "arrow -1", desc = "Move cursor up" },

  # Navigation
  { on = [ "<enter>" ], run = "plugin smart-enter", desc = "Enter directory" },
  { on = "-", run = "leave", desc = "Go to the parent directory" },
  { on = "<backspace>", run = "back", desc = "Got to previous directory" },

  # Operation
  { on = ":", run = 'shell "nu" --block --confirm', desc = "Open a shell" },
  { on = "C", run = 'plugin ouch', desc = "Compress" },

	# Copy
  { on = [ "%", "%" ], run = "copy path",             desc = "Copy the file path" },
  { on = [ "%", "d" ], run = "copy dirname",          desc = "Copy the directory path" },
  { on = [ "%", "f" ], run = "copy filename",         desc = "Copy the filename" },
  { on = [ "%", "n" ], run = "copy name_without_ext", desc = "Copy the filename without extension" },

  # Filter
  { on = "F", run = "plugin smart-filter", desc = "Smart filter" },

  # Spotting
  { on = "K", run = "spot", desc = "Spot hovered file" },

  # Seeking
	{ on = [ "<c-b>" ], run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = [ "<c-f>" ], run = "seek 5",  desc = "Seek down 5 units in the preview" },

  # Tabs
  { on = [ "<tab>", "<tab>"] , run = "tab_create --current", desc = "Open a new tab" },
  { on = [ "<tab>", "q" ], run = "close", desc = "Close the current tab" },
  { on = [ "[", "<tab>" ], run = "tab_switch -1 --relative", desc = "Switch to the previous tab" },
	{ on = [ "]", "<tab>" ], run = "tab_switch 1 --relative", desc = "Switch to the next tab" },
	{ on = [ "<tab>", "1" ], run = "tab_switch 0", desc = "Switch to first tab" },
	{ on = [ "<tab>", "2" ], run = "tab_switch 1", desc = "Switch to second tab" },
	{ on = [ "<tab>", "3" ], run = "tab_switch 2", desc = "Switch to third tab" },
	{ on = [ "<tab>", "4" ], run = "tab_switch 3", desc = "Switch to fourth tab" },
	{ on = [ "<tab>", "5" ], run = "tab_switch 4", desc = "Switch to fifth tab" },
	{ on = [ "<tab>", "6" ], run = "tab_switch 5", desc = "Switch to sixth tab" },
	{ on = [ "<tab>", "7" ], run = "tab_switch 6", desc = "Switch to seventh tab" },
	{ on = [ "<tab>", "8" ], run = "tab_switch 7", desc = "Switch to eighth tab" },
  { on = [ "<tab>", "9" ], run = "tab_switch 8", desc = "Switch to ninth tab" },

  # Misc
  { on = [ "g", "?" ], run = "help", desc = "Help" },
]

[spot]
append_keymap = [ 
  { on = "q", run = "close", desc = "Close spot" }, 
]

[input]
prepend_keymap = [
  { on = "<esc>", run = "close", desc = "Close input" },
]

[help]
prepend_keymap = [
  { on = "q", run = "close", desc = "Close help" },

  # Hopping
  { on = "{" , run = "arrow -6", desc = "Move cursor 6 items up"},
  { on = "}" , run = "arrow 6", desc = "Move cursor 6 items up"},
  { on = [ "<c-n>" ], run = "arrow 1", desc = "Move cursor down" },
  { on = [ "<c-p>" ], run = "arrow -1", desc = "Move cursor up" },
  { on = "<c-b>", run = "arrow -100%", desc = "Move cursor up one page" },
  { on = "<c-d>", run = "arrow 25", desc = "Move cursor down half page" },
  { on = "<c-f>", run = "arrow 100%",  desc = "Move cursor down one page" },
  { on = "<c-u>", run = "arrow -25", desc = "Move cursor up half page" },
  { on = "G",          run = "arrow 99999999",  desc = "Move cursor to the bottom" },
  { on = [ "g", "g" ], run = "arrow -99999999", desc = "Move cursor to the top" },

  # Filtering
  { on = "/", run = "filter", desc = "Filter help items" },
]
