# https://yazi-rs.github.io/docs/configuration/yazi

"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
linemode = "size"
ratio = [2, 3, 4]
scrolloff = 3
show_hidden = true
show_symlink = true
sort_dir_first = true
sort_sensitive = true

[opener]
compress = [
  { run = 'ouch compress "$@" archive.zip', desc = 'Compress (zip)' },
  { run = 'ouch compress "$@" archive.tar.gz', desc = 'Compress (tar.gz)' },
]
edit = [
	{ run = 'nvim "$@"', desc = "Edit", block = true },
]
extract = [
  { run = 'ouch decompress "$1"', desc = "Extract here" },
]
reveal = []

[open]
append_rules = [
  { name = "*", use = "compress" }
]

[plugin]
prepend_previewers = [
  { name = "*/", run = "folder", sync = true },
  { name = "*", run = "bat"},
]
