# https://yazi-rs.github.io/docs/configuration/yazi
# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/yazi-default.toml

"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
linemode = "size"
ratio = [2, 3, 4]
scrolloff = 3
show_hidden = true
show_symlink = true
sort_dir_first = true
sort_sensitive = true

[opener]
edit = [
	{ run = 'nvim "$@"', desc = "Edit", block = true, for = "unix" },
  { run = 'nvim %*', desc = "Edit", block = true, for = "windows" },
]
extract = [
  { run = 'ouch decompress --yes "$@"', desc = "Extract here", for = "unix" },
  { run = 'ouch decompress --yes %*', desc = "Extract here", for = "windows" },
]
view = [
  { run = 'open-in-windows-from-wsl.nu "$@"', desc = "View", for = "unix" }, # WSL
  { run = 'oculante %*', desc = "View", for = "windows" },
  { run = 'oculante -c "$@"', desc = "View", for = "macos" },
]

[open]
rules = [
	{ name = "*/", use = [ "open" ] },
	{ mime = "text/*", use = [ "edit" ] },
	{ mime = "image/*", use = [ "view" ] },
	{ mime = "{audio,video}/*", use = [ "play" ] },
  { name = "*.zip", use = [ "extract" ] },
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract" ] },
	{ mime = "application/{json,ndjson}", use = [ "edit" ] },
	{ mime = "*/javascript", use = [ "edit" ] },
	{ mime = "inode/empty", use = [ "edit" ] },
	{ mime = "vfs/*", use = "download" },
	{ name = "*", use = [ "open" ] },
]

[plugin]
previewers = [
  { mime = "application/{json,ndjson}", run = "json" },
  { mime = "image/*", run = "image" },
  { name = "*.zip", run = "ouch" },
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", run = "ouch" },
  { mime = "application/{octet-stream,dosexec,ms-*,microsoft.*}", run = "noop" }, # binary files - no preview
  { name = "*/", run = "folder", sync = true },
  { name = "*", run = "bat" },
]
