# https://yazi-rs.github.io/docs/configuration/yazi
# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/yazi-default.toml

"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
linemode = "size"
ratio = [2, 3, 4]
scrolloff = 3
show_hidden = true
show_symlink = true
sort_dir_first = true
sort_sensitive = true

[opener]
compress = [
  { run = 'ouch compress "$@" archive.zip', desc = 'Compress (zip)', for = "unix" },
  { run = 'ouch compress "%*" archive.zip', desc = 'Compress (zip)', for = "windows" },

  { run = 'ouch compress "$@" archive.tar.gz', desc = 'Compress (tar.gz)', for = "unix" },
  { run = 'ouch compress "%*" archive.tar.gz', desc = 'Compress (tar.gz)', for = "windows" },
]
edit = [
	{ run = 'nvim "$@"', desc = "Edit", block = true, for = "unix" },
  { run = 'nvim "%*"', desc = "Edit", block = true, for = "windows" },
]
extract = [
  { run = 'ouch decompress "$0"', desc = "Extract here", for = "unix" },
  { run = 'ouch decompress "%0"', desc = "Extract here", for = "windows" },
]

[open]
rules = [
	{ name = "*/", use = [ "open", "compress" ] },
	{ mime = "text/*", use = [ "edit" ] },
	{ mime = "image/*", use = [ "open" ] },
	{ mime = "{audio,video}/*", use = [ "play" ] },
  { name = "*.zip", use = ["extract"] },
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract" ] },
	{ mime = "application/{json,ndjson}", use = [ "edit" ] },
	{ mime = "*/javascript", use = [ "edit" ] },
	{ mime = "inode/empty", use = [ "edit" ] },
	{ mime = "vfs/*", use = "download" },
	{ name = "*", use = [ "open", "edit", "compress" ] },
]

[plugin]
previewers = [
  { mime = "application/{json,ndjson}", run = "json" },
  { name = "*.zip", run = "noop" },
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", run = "noop" },
  { mime = "application/{octet-stream,dosexec,ms-*}", run = "noop" }, # binary files - no preview
  { name = "*/", run = "folder", sync = true },
  { name = "*", run = "bat" },
]
