# https://yazi-rs.github.io/docs/configuration/yazi
# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/yazi-default.toml
[mgr]
linemode = "size_and_mtime"
ratio = [2, 3, 3]
scrolloff = 3
show_hidden = true
sort_sensitive = true

[preview]
max_width = 8192
max_height = 8192 

[opener]
edit = [
  { run = 'NVIM_APPNAME=vim nvim "$@"', desc = "Edit", block = true, for = "unix" },
  { run = 'set NVIM_APPNAME=vim&& nvim %*', desc = "Edit", block = true, for = "windows" },
  { run = 'nvim "$@"', desc = "Edit with Neovim", block = true, for = "unix" },
  { run = 'nvim %*', desc = "Edit with Neovim", block = true, for = "windows" },
]
extract = [
  { run = 'ouch decompress --yes "$@"', desc = "Extract here", for = "unix" },
  { run = 'ouch decompress --yes %*', desc = "Extract here", for = "windows" },
]
view = [
  { run = 'open-in-windows-from-wsl.sh "$@"', desc = "View", for = "unix" }, # WSL
]

[open]
rules = [
  { url = "*/", use = [ "open", "reveal" ] },
  { mime = "text/*", use = [ "edit", "reveal" ] },
  { mime = "image/*", use = [ "view", "reveal" ] },
  { mime = "{audio,video}/*", use = [ "play", "reveal" ] },
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal" ] },
  { mime = "application/{json,ndjson}", use = [ "edit", "reveal" ] },
  { mime = "*/javascript", use = [ "edit", "reveal" ] },
  { mime = "inode/empty", use = [ "edit", "reveal" ] },
  { mime = "vfs/{absent,stale}", use = "download" },
  { url = "*", use = [ "open", "reveal" ] },
]

[plugin]
previewers = [
  { url = "*/", run = "folder", sync = true },
  { mime = "text/*", run = "bat" },
  { mime = "*/javascript", run = "bat" },
  { mime = "application/{json,ndjson}", run = "json" },
  { mime = "image/*", run = "image" },
  { url = "*.zip", run = "ouch" },
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", run = "ouch" },
  { mime = "application/{octet-stream,dosexec,ms-*,microsoft.*}", run = "noop" }, # binary files - no preview
  { mime = "*", run = "file" },
]
