# https://docs.atuin.sh/configuration/config/

filter_mode = "workspace"
filter_mode_shell_up_key_binding = "global"
history_filter = [ "^v$", "^l$" ]
inline_height = 10
prefers_reduced_motion = true
show_help = false
show_tabs = false

[theme]
name = "nordstone"

